logging:
  pattern:
    console: "%d - %msg%n"
  file: E:/training/8.18/logFile
server:
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day15
    username: root
    password: root
  jpa:
    show-sql: true



